### ISSUE TITLE
polygon z-coordinates are removed using fix_polygon

### ISSUE THREAD

**Issue by just-davi** [gadomski/antimeridian#115]
It appears in the 0.3.5 release, a normalize method was added to the baseline.  Unfortunately, polygons that contain z-coordinates are not preserved when going through the normalize method.  

When looping through the coords list, the reassignment explicitly references point[1], but does not address point[2] if it exists.
A better solution might be to use *point[1:] to preserve any z-coordinates if they exist.

>>> from shapely import Polygon
>>> import antimeridian

>>> p = Polygon([[0, 0, 1], [0, 10, 2], [10, 10, 3], [10, 0, 4]])
>>> p.has_z
True
>>> p
<POLYGON Z ((0 0 1, 0 10 2, 10 10 3, 10 0 4, 0 0 1))>
>>> r = antimeridian.fix_polygon(p)
>>> r.has_z
False
>>> r
<POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0))>

**Comment by gadomski** [comment]
Thanks for the report! Fixed and released: https://github.com/gadomski/antimeridian/releases/tag/v0.3.6
