### ISSUE TITLE
Should __geo_interface__ be a property?

### ISSUE THREAD

**Issue by pjhartzell** [gadomski/antimeridian#120]
Per the [`__geo_interface__` gist](https://gist.github.com/sgillies/2217756#__geo_interface__) and implementation in packages like [shapely](https://github.com/shapely/shapely/blob/e9be9915689994c0737ddfecdcd6735cefa3dffc/shapely/geometry/base.py#L233-L236) and [geojson_pydantic](https://github.com/developmentseed/geojson-pydantic/blob/4c85ed5b54bdcca9ae75872b57b0e646cb513b27/geojson_pydantic/base.py#L18-L24), should the `__geo_interface__` method in antimeridian's [`GeoInterface`](https://github.com/gadomski/antimeridian/blob/7ec322a492abf44adcbd7167c251eac306b8ca32/src/antimeridian/_implementation.py#L55-L64) protocol be a property?

This question is motivated by a mypy error when passing a variable typed as a geojson_pydantic `Polygon | MultiPolygon` (which have a `__geo_interface__` _property_) to the `antimeridian.centroid` function, which is typed to accept a `Dict[str, Any] | GeoInterface` variable:

```
Argument 1 to "centroid" has incompatible type "Polygon | MultiPolygon"; expected "dict[str, Any] | GeoInterface"
```

Since the geojson_pydantic `Polygon` and `MultiPolygon` classes contain a `__geo_interface__` property, it seems that mypy should not be complaining. If I add a `@property` decorator to the antimeridian `GeoInterface` protocol, mypy is happy.

**Comment by gadomski** [comment]
Released in https://github.com/gadomski/antimeridian/releases/tag/v0.3.7
