### ISSUE TITLE
Wrong result at the Antimeridian

### ISSUE THREAD

**Issue by All4Gis** [gadomski/antimeridian#128]
Hi 

I believe there is a case where the results are not as expected. In this case it is crossing the antimeridian.

The geojson I am working with is this one [nosplit.json](https://github.com/user-attachments/files/16247596/nosplit.json)
.Which looks like this
<img width="1277" alt="Captura de pantalla 2024-07-16 a las 12 57 09" src="https://github.com/user-attachments/assets/ef5650f6-ee05-4ac5-939a-2f3685f6b8f9">

I have tried with the `fix_winding=False` flag but the result is just the inverse of the expected.
<img width="726" alt="Captura de pantalla 2024-07-16 a las 12 57 17" src="https://github.com/user-attachments/assets/359963ca-a27d-4e3b-b259-273887f7c386">

The expected result is this
<img width="699" alt="Captura de pantalla 2024-07-16 a las 12 57 24" src="https://github.com/user-attachments/assets/a22f23c4-d8fe-490b-9d40-16e2e702da04">

Any idea? Thanks for yur support

**Comment by gadomski** [comment]
I allows the winding order to be fixed automatically, and things worked ok:

```shell
$ antimeridian fix tests/data/input/issue-128.json > out.json
/Users/gadomski/Code/antimeridian/src/antimeridian/_implementation.py:593: FixWindingWarning: The exterior ring of this shape is wound clockwise. Since this is a common error in real-world geometries, this package is reversing the exterior coordinates of the input shape before running its algorithm. If you know that your input shape is correct (i.e. if your data encompasses both poles), pass `fix_winding=False`.
  FixWindingWarning.warn()
```

Result:

![issue-128](https://github.com/user-attachments/assets/3eac2555-da37-4e38-b126-6f70ae2c2801)

**Comment by All4Gis** [comment]
Ooops, you are right, sorry for the inconvenience. The fault is in my part
