### ISSUE TITLE
Document differences with `ogr2ogr -wrapdateline`

### ISSUE THREAD

**Issue by gadomski** [gadomski/antimeridian#147]
> We should note there are no other competing solutions to our knowledge? Is this true?

🤦🏼 of course GDAL has something for this: https://gdal.org/en/latest/programs/ogr2ogr.html#cmdoption-ogr2ogr-wrapdateline

However, a quick check shows it's not a like-for-like replacement. I'll do some digging and document the similarities and differences.

_Originally posted by @gadomski in https://github.com/gadomski/antimeridian/issues/137#issuecomment-2413625377_

**Comment by pjhartzell** [comment]
**fiona** also has an `antimeridian_cutting` option, which may be using gdal under the hood. 

https://fiona.readthedocs.io/en/stable/fiona.html#fiona.transform.transform_geom
