### ISSUE TITLE
Use great circles to calculate crossing latitude

### ISSUE THREAD

**Issue by teobouvard** [gadomski/antimeridian#153]
Hello,

I'm using the following polygon as input

```geojson
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                179.45064648,
                -65.47124346
            ],
            [
                178.30851744,
                -65.99077528
            ],
            [
                179.74817611,
                -66.51221218
            ],
            [
                -179.1162027,
                -65.98206677
            ]
        ]
    ]
}
```

When running

```console
antimeridian fix poly.json
```

I'm getting the following result

```geojson
{
    "type": "MultiPolygon",
    "coordinates": [
        [
            [
                [
                    180.0,
                    -65.726774
                ],
                [
                    179.45064648,
                    -65.47124346
                ],
                [
                    178.30851744,
                    -65.99077528
                ],
                [
                    179.74817611000003,
                    -66.51221218
                ],
                [
                    180.0,
                    -66.2469064
                ],
                [
                    180.0,
                    -65.726774
                ]
            ]
        ],
        [
            [
                [
                    -180.0,
                    -66.2469064
                ],
                [
                    -179.1162027,
                    -65.98206677
                ],
                [
                    -180.0,
                    -65.726774
                ],
                [
                    -180.0,
                    -66.2469064
                ]
            ]
        ]
    ]
}
```

which does not seem correct ? I was expecting the lines between the four vertices to be ~straight, but they're not. At least I did not expect it to be a discontinuity at the antimeridian, but I might make wrong assumptions. Could this be due to `crossing_latitude` not performing great circle intercepts with the 180° meridian ?

**Comment by gadomski** [comment]
> Could this be due to crossing_latitude not performing great circle intercepts with the 180° meridian ?

That's correct, we don't: https://github.com/gadomski/antimeridian/blob/0f4ccb1ebafe89a9bc02006178935e6ea8137287/src/antimeridian/_implementation.py#L501-L512

I'll mark this as an enhancement 👍🏼

**Comment by teobouvard** [comment]
Thanks, good to know! Would you be open to a PR for this ? I see the only dependencies are `shapely` and `numpy`, neither of which provide great-circle computations directly. Would you prefer to rely on a package providing this utility or have this implemented in the `antimeridian` package ?

**Comment by gadomski** [comment]
> Would you be open to a PR for this ? 

Yes! That would be excellent.

> Would you prefer to rely on a package providing this utility or have this implemented in the antimeridian package ?

I try to stay dependency-light if possible, and IIRC it's not that complicated of an equation, so if we can implement it directly w/o too much hassle that would be my preference.
