### ISSUE TITLE
Polygon returned is larger than expected

### ISSUE THREAD

**Issue by willbowditch** [gadomski/antimeridian#29]
Just testing this with a polygon which I think crosses the antimeridian, the polygon returned is different to what I was expecting:
```py
import shapely.wkt
import antimeridian
from shapely.geometry import shape
from shapely.validation import explain_validity

poly = shapely.wkt.loads("POLYGON ((179 0, 179 1, -179 1, -179 0, 179 0))")
explain_validity(poly) #'Valid Geometry'


shape(antimeridian.fix_shape(poly)).wkt #'POLYGON ((-180 1, -179 1, -179 0, -180 0, -180 -90, 180 -90, 180 0, 179 0, 179 1, 180 1, 180 90, -180 90, -180 1))'
```

I was expecting it to be something along the lines of `'MULTIPOLYGON (((179 0, 179 1, 180 1, 180 0, 179 0)), ((-180 1, -179 1, -179 0, -180 0, -180 1)))'`

**Comment by gadomski** [comment]
Your polygon is wound clockwise, meaning that it appears like a "hole". The algorithm correctly (IMO) creates a global polygon with a small hole around your region.

To get the a small, split polygon over the antimeridian, wind the other way:

```python
ccw_poly = shapely.wkt.loads("POLYGON ((179 0, -179 0, -179 1, 179 1, 179 0))")
print(explain_validity(ccw_poly))
print(shape(antimeridian.fix_shape(ccw_poly)).wkt)
```

Output:

```text
Valid Geometry
MULTIPOLYGON (((180 1, 179 1, 179 0, 180 0, 180 1)), ((-180 0, -179 0, -179 1, -180 1, -180 0)))
```

We have a file in our test suite that's similar to your original example (a "hole" over the antimeridian). This file is modeled after real world Sentinel-3 geometry we've encountered:

- [original](https://github.com/gadomski/antimeridian/blob/main/tests/data/input/both-poles.json)
- [fixed](https://github.com/gadomski/antimeridian/blob/main/tests/data/output/both-poles.json)

![image](https://github.com/gadomski/antimeridian/assets/58314/b2b3e077-6ed3-4118-a0b3-4e6820e869fd)

**Comment by willbowditch** [comment]
Ah I see, thanks for the explanation 👍
