### ISSUE TITLE
antimeridian fix returns inverted geometry

### ISSUE THREAD

**Issue by johntruckenbrodt** [gadomski/antimeridian#32]
Hi there. Thanks for the really handy tool. Any idea what is wrong with this geometry:
[test.txt](https://github.com/gadomski/antimeridian/files/11566843/test.txt)
(.json replaced with .txt so Github allows upload)

The returned geometry is basically an inversion of the actual geometry:
![image](https://github.com/gadomski/antimeridian/assets/18419439/09c342ba-c2c6-4c9a-9a17-30af178c244f)

here's a zoom:
![image](https://github.com/gadomski/antimeridian/assets/18419439/8b581db5-1040-4154-8a4b-133888d135a8)

**Comment by gadomski** [comment]
Your polygon is wound clockwise, meaning that the algorithm (correctly, IMO) think that it's a hole. To get your expected result, reverse the order of the coordinates.

For more information, check out this comment on a similar issue: https://github.com/gadomski/antimeridian/issues/29#issuecomment-1548277128

This is coming up repeatedly though, so maybe there's something we can do to help the user out ... I'll think about some sort of heuristic that we can apply in this case (or maybe a warning message).

**Comment by johntruckenbrodt** [comment]
Thanks a lot @gadomski and sorry for not checking more thoroughly.
