### ISSUE TITLE
Help folks out with improperly-wound inputs

### ISSUE THREAD

**Issue by gadomski** [gadomski/antimeridian#33]
To date, we've had two issues opened about unexpected results, where the problem was improperly-wound polygons:

- #29 
- #32 

We should help users out by either:

- Warning them that their polygon is _probably_ wound incorrectly
- Apply some sort of flag/fix

My initial thought is to check for double-pole crossings and reverse the coordinates by default in that case, with a flag to disable the behavior. Double-poles are pretty rare, and you usually know that you want it (e.g. sentinel-3), so the 80% solution might be to not produce double-poles by default. @pjhartzell do you have any thoughts on this one?

**Comment by pjhartzell** [comment]
>check for double-pole crossings and reverse the coordinates by default in that case

Will this also change/correct CW polygons that do not cross the antimeridian?

**Comment by gadomski** [comment]
Yes, because CW polygons that don't cross will create a double-pole (in the current implementation).

**Comment by pjhartzell** [comment]
We should give it some thought. It would be a nice feature.

**Comment by gadomski** [comment]
Agreed, I think it's _just_ in scope for the repo :-).
