### ISSUE TITLE
`fix_polygon` failing on Windows for point-on-antimeridian case

### ISSUE THREAD

**Issue by philipc2** [gadomski/antimeridian#54]
The following Polygons, which are point-on-antimeridian examples, do not split properly on Windows. Interestingly, these are different than the one described in #45. They also each include a point directly on the Pole, which may be leading to this inconsistency. Both of these points are from different datasets, where every other polygon is correctly represented except for these single instances. 

```Python
[[   0.           90.        ]
 [  90.           87.        ]
 [ 135.           85.76122798]
 [-180.           87.        ]
 [   0.           90.        ]]
```

```Python
[[ 144.           87.28061095]
 [ 180.           85.82395251]
 [-144.           87.28061095]
 [   0.           90.        ]
 [ 144.           87.28061095]]
```

### Windows Output 
```Python
POLYGON ((-180 90, -180 -90, 180 -90, 180 90, -180 90), (-180 87.00000000000009, -180 87.00000000000009, 0 90, 90 87.00000000000009, 135 85.76122797743554, 180 87.00000000000009, 180 90, -180 90, -180 87.00000000000009))
```

```Python
POLYGON ((-180 90, -180 -90, 180 -90, 180 90, -180 90), (-180 85.82395251186175, -144 87.28061095288037, 0 90, 143.9999999999999 87.28061095288037, 180 85.82395251186175, 180 85.82395251186175, 180 90, -180 90, -180 85.82395251186175))
```

### Mac (M1) Output
```Python
POLYGON ((-180 87.00000000000009, -180 87.00000000000009, 0 90, 90 87.00000000000009, 135 85.76122797743554, 180 87.00000000000009, 180 90, -180 90, -180 87.00000000000009))
```

```Python
POLYGON ((-180 85.82395251186175, -144 87.28061095288037, 0 90, 143.9999999999999 87.28061095288037, 180 85.82395251186175, 180 85.82395251186175, 180 90, -180 90, -180 85.82395251186175))
```

The Windows output contains the same polygon as the Mac output, however the added Polygon is due to this block starting at [line 313](https://github.com/gadomski/antimeridian/blob/3a1a44fab353a98a8c4b600d67ea9fc29c4e0983/src/antimeridian/_implementation.py#L313):
```Python
    if len(polygons) == 1:
        polygon = polygons[0]
        if shapely.is_ccw(polygon.exterior):
            return polygon
        else:
            return Polygon(
                [(-180, 90), (-180, -90), (180, -90), (180, 90)],
                [polygon.exterior.coords],
            )
    else:
        return MultiPolygon(polygons)
```

 `shapely.is_ccw` returns True on Mac but False on Windows.

**Comment by gadomski** [comment]
I can't easily reproduce this, because my Windoze box is only set up for WSL-based dev, but it's fishy to me that `shapely.is_ccw` produces different results. My recommendation would be to isolate that issue alone, and file it on shapely if it truely is different on windows. I'd also check your shapely version on your windows box.

I can't do much in this package is `shapely.is_ccw` produces different results on different OSes.

**Comment by philipc2** [comment]
Just tested it again and the splitting is working as expected now, it appears to have been because I had a much older version of Shapely and GEOS installed.
