### ISSUE TITLE
Split strategy produces invalid multipolygon from invalid polygon

### ISSUE THREAD

**Issue by philvarner** [gadomski/antimeridian#55]
I think the gist of this issue is how the antimeridian functions should handle invalid GeoJSON inputs. When an invalid GeoJSON polygon or multipolygon is input, the split antimeridian output is usually also invalid. Should this be the case, or should antimeridian throw an exception for invalid geometries?

This example is from the sentinel2 scene in the stactools-sentinel2 package `sentinel2/tests/data-files/S2A_MSIL1C_20200717T221941_R029_T01LAC_20200717T234135.SAFE/MTD_MSIL1C.xml`

The polygon created from the metadata for this is:

{"type": "Polygon", "coordinates": [[[180.0, -15.355911], [-179.70343, -15.36019], [-179.71667, -16.351724], [180.0, -16.34738], [179.256949, -16.335986], [179.275178, -15.345454], [180.0, -15.355911]]]}

Which according to shapely, has a self-intersection. However, running antimeridian with split strategy produces another (invalid) MultiPolygon:

{"type": "MultiPolygon", "coordinates": [[[[180.0, -15.3580514], [180.0, -15.355911], [179.27517799999998, -15.345454], [179.25694899999996, -16.335986], [180.0, -16.34738], [180.0, -16.3495529], [180.0, -15.3580514]]], [[[-180.0, -16.3495529], [-179.71667, -16.351724], [-179.70343, -15.36019], [-180.0, -15.3580514], [-180.0, -16.3495529]]]]}

which when shapely "make_valid" is run on it, produces this:

{"type": "GeometryCollection", "geometries": [{"type": "Polygon", "coordinates": [[[179.25694899999996, -16.335986], [179.27517799999998, -15.345454], [180.0, -15.355911], [180.0, -15.3580514], [180.29657, -15.36019], [180.28333, -16.351724], [180.0, -16.3495529], [180.0, -16.34738], [179.25694899999996, -16.335986]]]}, {"type": "LineString", "coordinates": [[180.0, -16.34738], [180.0, -15.3580514]]}]}

Running make_valid on the original polygon fixes the stray line, and yields:

{"type": "MultiPolygon", "coordinates": [[[[180.0, -16.34738], [-179.71667, -16.351724], [-179.70343, -15.36019], [179.27498539857692, -15.355919624709193], [179.256949, -16.335986], [180.0, -16.34738]]], [[[179.275178, -15.345454], [180.0, -15.355911], [179.27498539857692, -15.355919624709193], [179.275178, -15.345454]]]]}

indicating the issue with the MultiPolygon is that one of the polygons has a line jutting out of it.

**Comment by gadomski** [comment]
> I think the gist of this issue is how the antimeridian functions should handle invalid GeoJSON inputs. When an invalid GeoJSON polygon or multipolygon is input, the split antimeridian output is usually also invalid. Should this be the case, or should antimeridian throw an exception for invalid geometries?

My instinct is "garbage in, garbage out". If the problem is a common one that a user might not understand (e.g. https://github.com/gadomski/antimeridian/pull/39), we can help folks out by fixing. But running `make_valid` on every input feels like a bridge too far, especially since that's simple for a user to do before calling our package. So right now my position is to do nothing to correct invalid inputs.

This is partially motivated by [real-world examples](https://github.com/gadomski/antimeridian/blob/main/tests/data/input/overlap.json), e.g. sentinel-5p, which have invalid input shapes because they overlap themselves:

![overlap](https://github.com/gadomski/antimeridian/assets/58314/62aa88be-a0bc-44a9-ad53-0973a3056055)

**Comment by philvarner** [comment]
Agree. I think somewhere (not necessarily in antimeridian), I would want to see an example of using is_valid to validate if a pre-existing geometry is valid before doing anything with it, and use of make_valid to "fix" it before doing operations like antimeridian splitting or centroid calculation.
