### ISSUE TITLE
using segment_geojson causes there to be zig zags on the anti meridian

### ISSUE THREAD

**Issue by mjones1818** [gadomski/antimeridian#89]
Using the segment_geojson to split a polygon into multilines causes there to be zig zags were the lines should meet. Any help would be appreciated! 
![image001](https://github.com/gadomski/antimeridian/assets/67018042/f7d2772d-c5cc-4d39-b214-8e6c87d4a68e)
![image001-1](https://github.com/gadomski/antimeridian/assets/67018042/2a6603df-930b-4172-8f2e-4b247bcebd3b)

**Comment by gadomski** [comment]
This looks like an invalid split — can you provide the original GeoJSON so I can debug directly? Thanks!

**Comment by mjones1818** [comment]
Absolutely! Thank you for the quick response. Here is the original polygon I want to split followed by the bad split. 
`{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "coordinates": [
          [
            [
              -151.75,
              56.750012
            ],
            [
              -137,
              53.366668
            ],
            [
              -135,
              52.716667
            ],
            [
              -133.75,
              51
            ],
            [
              -128,
              48.333333
            ],
            [
              -127.916675,
              48.166667
            ],
            [
              -126.5,
              45
            ],
            [
              -126.9,
              40.983333
            ],
            [
              -127,
              40.833333
            ],
            [
              -127,
              37.500006
            ],
            [
              -126.933333,
              36.450012
            ],
            [
              -125.833333,
              35.5
            ],
            [
              -124.2,
              36
            ],
            [
              -123.25,
              34.5
            ],
            [
              -120.833333,
              30.75
            ],
            [
              -120,
              30
            ],
            [
              -120,
              3.5
            ],
            [
              -145,
              3.5
            ],
            [
              -155,
              -5
            ],
            [
              -179.983346,
              -4.98335
            ],
            [
              -179.983346,
              3.5
            ],
            [
              -180.01665,
              3.5
            ],
            [
              -200.01665,
              3.5
            ],
            [
              -200.01665,
              0
            ],
            [
              -219,
              0
            ],
            [
              -219,
              3.5
            ],
            [
              -227,
              3.5
            ],
            [
              -230,
              7
            ],
            [
              -230.01665,
              20.98335
            ],
            [
              -205.01665,
              21
            ],
            [
              -205.01665,
              26.98335
            ],
            [
              -195.01665,
              26.98335
            ],
            [
              -195,
              43
            ],
            [
              -197.083333,
              45.7
            ],
            [
              -179.98335,
              49.68334
            ],
            [
              -176.566667,
              50.116683
            ],
            [
              -167.816667,
              51.4
            ],
            [
              -160,
              53.5
            ],
            [
              -153,
              56
            ],
            [
              -151.75,
              56.750012
            ]
          ]
        ],
        "type": "Polygon"
      },
      "properties": {
        "FIR_UIR_Identifier": "KZAK",
        "exclude": "",
        "fill": "#45F4F7",
        "fill-opacity": 0.6,
        "key": "SUSAUFKZAKZOZXF",
        "region": "pacific",
        "stroke": "#555555",
        "stroke-opacity": 1,
        "stroke-width": 2
      },
      "type": "Feature"
    }
  ]
}`

`{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "coordinates": [
          [
            [
              -180,
              47.643312
            ],
            [
              -179.98335,
              49.68334
            ],
            [
              -176.566667,
              50.116683
            ],
            [
              -167.816667,
              51.4
            ],
            [
              -160,
              53.5
            ],
            [
              -153,
              56
            ],
            [
              -151.75,
              56.750012
            ],
            [
              -137,
              53.366668
            ],
            [
              -135,
              52.716667
            ],
            [
              -133.75,
              51
            ],
            [
              -128,
              48.333333
            ],
            [
              -127.916675,
              48.166667
            ],
            [
              -126.5,
              45
            ],
            [
              -126.9,
              40.983333
            ],
            [
              -127,
              40.833333
            ],
            [
              -127,
              37.500006
            ],
            [
              -126.933333,
              36.450012
            ],
            [
              -125.833333,
              35.5
            ],
            [
              -124.2,
              36
            ],
            [
              -123.25,
              34.5
            ],
            [
              -120.833333,
              30.75
            ],
            [
              -120,
              30
            ],
            [
              -120,
              3.5
            ],
            [
              -145,
              3.5
            ],
            [
              -155,
              -5
            ],
            [
              -179.983346,
              -4.98335
            ],
            [
              -179.983346,
              3.5
            ],
            [
              -180,
              3.5
            ]
          ],
          [
            [
              180,
              3.5
            ],
            [
              179.98335,
              3.5
            ],
            [
              159.98335,
              3.5
            ],
            [
              159.98335,
              0
            ],
            [
              141,
              0
            ],
            [
              141,
              3.5
            ],
            [
              133,
              3.5
            ],
            [
              130,
              7
            ],
            [
              129.98335,
              20.98335
            ],
            [
              154.98335,
              21
            ],
            [
              154.98335,
              26.98335
            ],
            [
              164.98335,
              26.98335
            ],
            [
              165,
              43
            ],
            [
              162.916667,
              45.7
            ],
            [
              180,
              47.643312
            ]
          ]
        ],
        "type": "MultiLineString"
      },
      "properties": {
        "FIR_UIR_Identifier": "KZAK",
        "exclude": "",
        "fill": "#45F4F7",
        "fill-opacity": 0.6,
        "key": "SUSAUFKZAKZOZXF",
        "region": "pacific",
        "stroke": "#555555",
        "stroke-opacity": 1,
        "stroke-width": 2
      },
      "type": "Feature"
    }
  ]
}
`
![Capture3](https://github.com/gadomski/antimeridian/assets/67018042/b9126959-1128-4e2b-ab40-fa9457da0dd5)
![Capture4](https://github.com/gadomski/antimeridian/assets/67018042/50a1226a-2b28-4bc8-bafc-30b1f1ab5965)

**Comment by mjones1818** [comment]
@gadomski any update on this issue? Appreciate all the help on this.

**Comment by gadomski** [comment]
It's in my TODO queue, which unfortunately is long :-). But I haven't dropped it. Thanks for your patience.

**Comment by gadomski** [comment]
@amaberg finally looking at this issue, I can't reproduce w/ v0.3.3:

```shell
$ pip freeze | grep antimeridian
antimeridian==0.3.3
$ antimeridian fix tests/data/input/issues-89.json
/Users/gadomski/Code/gadomski/antimeridian/src/antimeridian/_implementation.py:533: FixWindingWarning: The exterior ring of this shape is wound clockwise. Since this is a common error in real-world geometries, this package is reversing the exterior coordinates of the input shape before running its algorithm. If you know that your input shape is correct (i.e. if your data encompasses both poles), pass `fix_winding=False`.
  FixWindingWarning.warn()
{"type": "FeatureCollection", "features": [{"geometry": {"type": "MultiPolygon", "coordinates": [[[[-180.0, 3.5], [-179.983346, 3.5], [-179.983346, -4.98335], [-155.0, -5.0], [-145.0, 3.5], [-120.0, 3.5], [-120.0, 30.0], [-120.833333, 30.75], [-123.25, 34.5], [-124.2, 36.0], [-125.833333, 35.5], [-126.933333, 36.450012], [-127.0, 37.500006], [-127.0, 40.833333], [-126.9, 40.983333], [-126.5, 45.0], [-127.916675, 48.166667], [-128.0, 48.333333], [-133.75, 51.0], [-135.0, 52.716667], [-137.0, 53.366668], [-151.75, 56.750012], [-153.0, 56.0], [-160.0, 53.5], [-167.816667, 51.4], [-176.566667, 50.116683], [-179.98335, 49.68334], [-180.0, 47.6433115], [-180.0, 3.5]]], [[[180.0, 47.6433115], [162.91666699999996, 45.7], [165.0, 43.0], [164.98334999999997, 26.98335], [154.98334999999997, 26.98335], [154.98334999999997, 21.0], [129.98334999999997, 20.98335], [130.0, 7.0], [133.0, 3.5], [141.0, 3.5], [141.0, 0.0], [159.98334999999997, 0.0], [159.98334999999997, 3.5], [179.98334999999997, 3.5], [180.0, 3.5], [180.0, 47.6433115]]]]}, "properties": {"FIR_UIR_Identifier": "KZAK", "exclude": "", "fill": "#45F4F7", "fill-opacity": 0.6, "key": "SUSAUFKZAKZOZXF", "region": "pacific", "stroke": "#555555", "stroke-opacity": 1, "stroke-width": 2}, "type": "Feature"}]}
```

![issues-89](https://github.com/gadomski/antimeridian/assets/58314/76a93c29-598d-4d40-aff9-fe0211bf5b35)

![image](https://github.com/gadomski/antimeridian/assets/58314/13c69d65-bc63-49fc-9f8b-9be366b22ab7)

Please re-open if I've missed something.
